config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :stocks, only: [:index, :new, :show, :create]

  root 'welcome#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  # extend FriendlyId
  # friendly_id :symbol, use: :slugged

  # http://stackoverflow.com/questions/24226378/rails-routes-with-name-instead-of-id-url-parameters
  # https://github.com/norman/friendly_id
  # https://gorails.com/episodes/pretty-urls-with-friendly-id

  # def to_param
  #   symbol
  # end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  include ApplicationHelper

  def index
    redirect_to new_stock_path
  end

  def new
    if current_user
      @stock = Stock.new
    else
      redirect_to login_path
    end
  end

  def show
    if current_user
      @stock = Stock.find(params[:id])
    else
      redirect_to login_path
    end
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to stock_path(@stock)
    else
      render "new"
    end
  end



  private
  def stock_params
    params.require(:stock).permit(:symbol)
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_stock_data.html.erb
<% if @stock %>
  <div id="description-news">
    <div class="company-description">
    <% # a div to display the description of companies %>
      <table>
        <thead>
          <tr>
            <th class="news-title" colspan="2"> Company Profile</th>
          </tr>
        </thead>
        <tbody>
          <% @company_profile.each do |detail, profile|%>
          <tr>
            <td class="company-detail"><%= detail.capitalize %></td>
            <td class="company-profile"><%= profile %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="news-headline">
    <% # a div to display the news of equity %>
    <h3 class="headline">Headlines</h3>
      <% @news.each do |anchor_element| %>
        <li class="news"><a href="<%= anchor_element[:href] %>" class="link" target=_><%= anchor_element[:title] %></a>
          <span class="publisher"><%=anchor_element[:publisher]%></span> <span class="published_date"><%=anchor_element[:published_date] %></span></li>
      <% end %>
    </div>
  </div>





  <div class="chart">
    <!-- if symbole exists, plot the data

<!--   <img src="<%=@plot_data_img%>" /> -->
  </div>

    <div class="comment-box">
      <!-- comment box for a specific stock -->
      <div class="comment-box-form">
         <form id="comment-form" action="/stocks/<%=@stock.symbol%>/period/<%=params[:period]%>" method="post">
          <label for="comment"></label>
          <input id="comment" type="text" name="comment"  placeholder="Leave a Comment">
          <input type="submit" value="Submit">
        </form>
      </div>

      <% @comment.each do |content| %>
        <%= erb :_comment, :locals => {:content => content}  %>
        <% #don't need to pass @stocks as local since it's an instance variable %>
      <% end # each each%>
  </div>

  <div class="table-data">
    <!-- if symbole exists -->
    <% if @data %>
      <table>
        <thead>
          <tr>
            <th class="tbl-title" colspan="6"> Prices for <%=
            "Symbol = " + @stock.symbol%></th>
          </tr>
          <tr class="tbl-header">
              <th>Date</th>
              <th>Open</th>
              <th>High</th>
              <th>Low</th>
              <th>Close</th>
              <th>Volume</th>
           </tr>
        </thead>
        <tbody>
            <% @data.each_with_index do |data, index| %>
              <% if index.even? %>
               <tr class="tbl-row-even">
                  <td><%= data.date %></td>
                  <td><%= data.open.round(3) %></td>
                  <td><%= data.high.round(3) %></td>
                  <td><%= data.low.round(3) %></td>
                  <td><%= data.close.round(3) %></td>
                  <td><%= Stock.separate_comma(data.volume.to_i) %></td>
               </tr>
              <% else %>
               <tr class="tbl-row-odd">
                  <td><%= data.date %></td>
                  <td><%= data.open.round(3) %></td>
                  <td><%= data.high.round(3) %></td>
                  <td><%= data.low.round(3) %></td>
                  <td><%= data.close.round(3) %></td>
                  <td><%= Stock.separate_comma(data.volume.to_i) %></td>
               </tr>
              <%end #end if%>
         <%end #end each%>
        </tbody>
      </table>
    <%elsif @data == "not valid"%>
      <li class="sym-error"> The symbol you entered is not valid. Please pick a valid symbol!</li>
    <%end #end if%>
  </div>
<% end #end if %> -->

app/views/stocks/new.html.erb
<header>
  <div class="logout">
    <%= form_for :session, url: logout_path, method: :delete do |f| %>
      <%= f.submit "Logout", class: "logout-btn" %>
    <% end %>
  </div>

  <div class="account">
    <!-- adding "url: edit_user_path" does not work for some reasons -->
    <%= form_for :user do |f| %>
      <%= f.submit "Account", class: "account-btn" %>
    <% end %>
  </div>
</header>

<div class="symbol-box">
  <%= form_for :stock, url: stocks_path do |f| %>
    <%= f.text_field :symbol, id: "symbol", placeholder: "Enter a Stock Symbol" %><br>
    <%= f.submit "Search" %>
  <% end %>
  <p> Note: if the interval field is left blank, the default value of 30 days will be used.</p>
</div>

app/views/stocks/show.html.erb
<header>
  <div class="logout">
    <%= form_for :session, url: logout_path, method: :delete do |f| %>
      <%= f.submit "Logout", class: "logout-btn" %>
    <% end %>
  </div>

  <div class="account">
    <%= form_for :user, url: edit_user_path do |f| %>
      <%= f.submit "Account", class: "account-btn" %>
    <% end %>
  </div>
</header>

<main>
<div id="page-layout-data">
</div>
</main>
<div class="symbol-box">
  <%= form_for :stock, url: stocks_path do |f| %>
    <%= f.text_field :symbol, id: "symbol", placeholder: "Enter a Stock Symbol" %><br>
    <%= f.submit "Search" %>
  <% end %>
  <p> Note: if the interval field is left blank, the default value of 30 days will be used.</p>
</div>

<p>The symbol is: <%= @stock.symbol %></p>